//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daigassou.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList KeyBinding13 {
            get {
                return ((global::System.Collections.ArrayList)(this["KeyBinding13"]));
            }
            set {
                this["KeyBinding13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StartKey {
            get {
                return ((int)(this["StartKey"]));
            }
            set {
                this["StartKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList CtrlKeyBinding {
            get {
                return ((global::System.Collections.ArrayList)(this["CtrlKeyBinding"]));
            }
            set {
                this["CtrlKeyBinding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsEightKeyLayout {
            get {
                return ((bool)(this["IsEightKeyLayout"]));
            }
            set {
                this["IsEightKeyLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList KeyBinding37 {
            get {
                return ((global::System.Collections.ArrayList)(this["KeyBinding37"]));
            }
            set {
                this["KeyBinding37"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public uint MinEventMs {
            get {
                return ((uint)(this["MinEventMs"]));
            }
            set {
                this["MinEventMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public uint MinChordMs {
            get {
                return ((uint)(this["MinChordMs"]));
            }
            set {
                this["MinChordMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ntp3.aliyun.com")]
        public string NtpServer {
            get {
                return ((string)(this["NtpServer"]));
            }
            set {
                this["NtpServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoChord {
            get {
                return ((bool)(this["AutoChord"]));
            }
            set {
                this["AutoChord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\"Name\":\"Start\",\"Key\":121,\"Modifiers\":2,\"Enabled\":true},{\"Name\":\"Stop\",\"Key\":122" +
            ",\"Modifiers\":2,\"Enabled\":true},{\"Name\":\"PitchUp\",\"Key\":119,\"Modifiers\":2,\"Enable" +
            "d\":true},{\"Name\":\"PitchDown\",\"Key\":120,\"Modifiers\":2,\"Enabled\":true}]")]
        public string HotKeyBinding {
            get {
                return ((string)(this["HotKeyBinding"]));
            }
            set {
                this["HotKeyBinding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isUsingWinPCap {
            get {
                return ((bool)(this["isUsingWinPCap"]));
            }
            set {
                this["isUsingWinPCap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isUsingAnalysis {
            get {
                return ((bool)(this["isUsingAnalysis"]));
            }
            set {
                this["isUsingAnalysis"] = value;
            }
        }
    }
}
